{"name": "test_log_in", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../resorses/prod_conf.yaml'", "trace": "self = <login_test.TestLogin object at 0x000001F64397BF40>\n\n    def test_log_in(self):\n        # SignIn(Session.get_driver(), 'https://www.google.com/account/about/?hl=ru').login('xsxtestxsx97@gmail.com', '7rHXgT7LU4qGwms')\n>       SignIn(Session.get_driver(), getDataFromConfig('BASE_URL')).login(getDataFromConfig('EMAIL'), getDataFromConfig('PASSWORD'))\n\ntests\\login_test.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nkey = 'BASE_URL'\n\n    def getDataFromConfig(key):\n>       with open('../resorses/prod_conf.yaml') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../resorses/prod_conf.yaml'\n\nresorses\\pars_values.py:15: FileNotFoundError"}, "attachments": [{"name": "Current URL", "source": "43bf49a8-50ad-4d8b-84f0-d7d271a956ac-attachment.uri", "type": "text/uri-list"}, {"name": "Screenshot", "source": "f9f8a993-df5e-41e3-b543-7a6078f96be1-attachment.png", "type": "image/png"}], "start": 1658493015674, "stop": 1658493015674, "uuid": "5b59a834-793a-42a1-9780-e6abd60870cc", "historyId": "a3851f61166f88ea3141e43fd722fb42", "testCaseId": "492dfcd180548bbbcd56a712f212b3b2", "fullName": "tests.login_test.TestLogin#test_log_in", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('start_session')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-12H3A8H"}, {"name": "thread", "value": "34348-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}