{"name": "test_log_in", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'prod_conf.yaml'", "trace": "self = <login_test.TestLogin object at 0x00000227D52CE070>\n\n    def test_log_in(self):\n        # SignIn(Session.get_driver(), 'https://www.google.com/account/about/?hl=ru').login('xsxtestxsx97@gmail.com', '7rHXgT7LU4qGwms')\n>       SignIn(Session.get_driver(), getDataFromConfig('BASE_URL')).login(getDataFromConfig('EMAIL'), getDataFromConfig('PASSWORD'))\n\ntests\\login_test.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nkey = 'BASE_URL'\n\n    def getDataFromConfig(key):\n>       with open('prod_conf.yaml') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'prod_conf.yaml'\n\nresorses\\pars_values.py:15: FileNotFoundError"}, "attachments": [{"name": "Current URL", "source": "21584b9d-be9e-4c25-bb20-6a0589405f59-attachment.uri", "type": "text/uri-list"}, {"name": "Screenshot", "source": "fb2a7b6a-bc51-411a-a0eb-096bb07ba58f-attachment.png", "type": "image/png"}], "start": 1658493681048, "stop": 1658493681049, "uuid": "a1cfa9b7-fb3c-45ff-ac00-7a9ab159b8a2", "historyId": "a3851f61166f88ea3141e43fd722fb42", "testCaseId": "492dfcd180548bbbcd56a712f212b3b2", "fullName": "tests.login_test.TestLogin#test_log_in", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('start_session')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-12H3A8H"}, {"name": "thread", "value": "33884-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}